mugen_python_mots = {
    "print": "affiche",
    "append": "ajoute",
    "remove": "supprime",
    "del": "efface",
    "len": "long",
    "sort": "trie",
    "extend": "etend",
    "insert": "inser",
    "pop": "extrais",
    "index": "indice",
    "count": "compte",
    "reverse": "inverse",
    "dict": "dict",
    "keys": "cles",
    "values": "valeurs",
    "items": "elements",
    "get": "trouve",
    "clear": "vider",
    "in": "dans",
    "if": "si",
    "else": "sinon",
    "and": "et",
    "or": "ou",
    "elif": "sinonsi",
}
